---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - global_vars.yml
  tasks:
    - name: Stop Test
      uri:
        url: "http://{{ controller_ip }}:{{ controller_port }}/api/v1.0/te/stop"
        method: POST
        body_format: json
        status_code: 200
      register: stop
