---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - global_vars.yml
  tasks:
    - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - '{{ansible_distribution}}.yaml'
            - '{{ansible_os_family}}.yaml'
            - group_var.yml
          paths:
            - 'vars'
    - name: Stop Test
      uri:
        url: "http://{{ controller_ip }}:{{ controller_port }}/api/v1.0/te/stop"
        method: POST
        body_format: json
        status_code: 200
      register: stop
